import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#00488d',
        'primary-container': '#005fb8',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468b',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a8c8ff',
        secondary: '#1b6d24',
        'secondary-container': '#a0f399',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        'secondary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#88d982',
        tertiary: '#96000f',
        'tertiary-container': '#bb1f21',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#410003',
        'on-tertiary-fixed-variant': '#93000e',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb4ac',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-tint': '#005db5',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424752',
        outline: '#727783',
        'outline-variant': '#c2c6d4',
        inverse: {
          surface: '#2e3132',
          'on-surface': '#f0f1f2',
          primary: '#a8c8ff',
        },
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};

export default config;
